### ISSUE TITLE
Support escaping HTML entities during serialization

### ISSUE THREAD

**Issue by codemonstur** [codemonstur/simplexml#10]
Currently simplexml only supports unescaping HTML entities. There is no support for going in the opposite direction during serialization.

Feature requested by @Geolykt in #9

**Comment by codemonstur** [comment]
@Geolykt what did you do to me! Support HTML entities escaping.. Yeah, easy I said. And then this page needs to get added: https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references.

**Comment by Geolykt** [comment]
FYI, HTML entity escaping is not a feature I need at this point in time. I only need XML escaping, and that seems to work at least to the degree I need it to.

That being said, I completely agree that this library should be able to support that if it already does the reverse step.

**Comment by codemonstur** [comment]
Yeah, I know you don't really need it. But I agree that it should be supported. The actual code is pretty easy, but that giant long list of entities, ugh. This will take some time :)

**Comment by Geolykt** [comment]
Don't you already have https://github.com/codemonstur/simplexml/blob/ae2fa61f7c107213a610c635ea2f697264f9f1eb/src/main/java/xmlparser/utils/Escaping.java#L51-L110 for this or is it not complete enough?

**Comment by codemonstur** [comment]
Not complete enough, it only has HTML 3.2. All of HTML 5.0 is missing. Another problem I want to fix.

**Comment by codemonstur** [comment]
Done in 3.2.0
