### ISSUE TITLE
Unable to import Using Gradle

### ISSUE THREAD

**Issue by grndvl1** [codemonstur/simplexml#7]
Using gradle I added you to project by setting 

```
repositories {
    mavenCentral()
    maven { setUrl("https://jitpack.io") }
}

dependencies {
    implementation("org.json:json:20230227")
    implementation("com.github.codemonstur:simplexml:3.1.0")

```

Then in my java class I try and add the import and it does not recognize your user name.  Its funny code lab wants the import to point to  ```com.github.codemonsture92.SimpleXml;```. But still I can't get this to work ```import com.github.codemonstur.*;```

**Comment by codemonstur** [comment]
The package name for the code is `xmlparser.*`. So `import xmlparser.XmlParser;`. And I see now that I have neglected to update the readme with this. My bad.
